CREATE USER 'labrandor'@'localhost'
IDENTIFIED WITH mysql_native_password
AS '*E5289BF40B50FC465B359E0FC649B7671BFA05B2';

GRANT USAGE ON *.* TO 'labrandor'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER,
CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER
ON `labrandor`.* TO 'labrandor'@'localhost';

CREATE USER 'lab-master'@'localhost' 
IDENTIFIED WITH mysql_native_password 
AS '*7ED7D51F89DAF8A1FA70D73659BD53B3882C1748';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, FILE, INDEX, ALTER,
SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
ON *.* TO 'lab-master'@'localhost' WITH GRANT OPTION;